### ISSUE TITLE
why "w_glob_client = FedAvg(w_locals_client)" error

### ISSUE THREAD

**Issue by hnust-xxq** [ZJU-CNLAB/PipeSFL#1]
raceback (most recent call last):
  File "/SFLV_1F1B/PipeSFL/PipeSFLV1_ResNet50_Cifar100.py", line 723, in <module>
    w_glob_client = FedAvg(w_locals_client)
  File "/SFLV_1F1B/PipeSFL/PipeSFLV1_ResNet50_Cifar100.py", line 136, in FedAvg
    w_avg = copy.deepcopy(w[0])
  File "<string>", line 2, in __getitem__
  File "/root/miniconda3/lib/python3.10/multiprocessing/managers.py", line 833, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Unserializable message: Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/multiprocessing/managers.py", line 308, in serve_client
  File "/root/miniconda3/lib/python3.10/multiprocessing/connection.py", line 211, in send
  File "/root/miniconda3/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
  File "/root/miniconda3/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 429, in reduce_storage
  File "/root/miniconda3/lib/python3.10/multiprocessing/reduction.py", line 198, in DupFd
  File "/root/miniconda3/lib/python3.10/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files

**Comment by yunqigao-zju** [comment]
I can hardly know why “w_glob_client = FedAvg(w_locals_client)” error, could you provide some more detailed information?
